<a href="https://colab.research.google.com/github/Vyshnavi262007/AI-ML-Projects/blob/main/sentiment_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
sentences = [
    "I love this movie",
    "This movie is amazing",
    "I really enjoyed this film",
    "The movie was fantastic",
    "I hate this movie",
    "This movie is terrible",
    "I really disliked this film",
    "The movie was horrible"
]

labels = [1, 1, 1, 1, 0, 0, 0, 0]

In [2]:
import tensorflow as tf

vectorizer = tf.keras.layers.TextVectorization(
    max_tokens=1000,
    output_mode="int",
    output_sequence_length=10
)

vectorizer.adapt(sentences)

In [3]:
print(vectorizer.get_vocabulary())

['', '[UNK]', np.str_('this'), np.str_('movie'), np.str_('i'), np.str_('was'), np.str_('the'), np.str_('really'), np.str_('is'), np.str_('film'), np.str_('terrible'), np.str_('love'), np.str_('horrible'), np.str_('hate'), np.str_('fantastic'), np.str_('enjoyed'), np.str_('disliked'), np.str_('amazing')]


In [4]:
X = vectorizer(tf.constant(sentences))

print(X)

tf.Tensor(
[[ 4 11  2  3  0  0  0  0  0  0]
 [ 2  3  8 17  0  0  0  0  0  0]
 [ 4  7 15  2  9  0  0  0  0  0]
 [ 6  3  5 14  0  0  0  0  0  0]
 [ 4 13  2  3  0  0  0  0  0  0]
 [ 2  3  8 10  0  0  0  0  0  0]
 [ 4  7 16  2  9  0  0  0  0  0]
 [ 6  3  5 12  0  0  0  0  0  0]], shape=(8, 10), dtype=int64)


In [5]:
model = tf.keras.Sequential([
    tf.keras.layers.Embedding(
        input_dim=1000,
        output_dim=16
    ),

    tf.keras.layers.LSTM(32),

    tf.keras.layers.Dense(
        1,
        activation="sigmoid"
    )
])

In [6]:
model.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

In [8]:
model.fit(
    X,
    tf.constant(labels),
    epochs=20,
    verbose=1
)

Epoch 1/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.5000 - loss: 0.6930
Epoch 2/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.5000 - loss: 0.6929
Epoch 3/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5000 - loss: 0.6927
Epoch 4/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.6926
Epoch 5/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.6924
Epoch 6/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.6923
Epoch 7/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5000 - loss: 0.6921
Epoch 8/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5000 - loss: 0.6919
Epoch 9/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.6917
Epoch 10/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.6250 - loss: 0.6915
Epoch 11/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.7500 - loss: 0.6912
Epoch 12/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.8750 - loss: 0.6909
Epo

In [9]:
test_sentence = ["I really love this film"]

test_vector = vectorizer(
    tf.constant(test_sentence)
)

prediction = model.predict(test_vector)

print(prediction)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 387ms/step
[[0.5047792]]


In [10]:
if prediction[0][0] >= 0.5:
    print("Positive 😊")
else:
    print("Negative 😞")

Positive 😊
